### PR TITLE
Cast set_location arguments to float

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Addresses https://github.com/appium/python-client/issues/331

### CODE REVIEW

**Comment by nunessf** [comment]
Probably not the place to ask this, but when there might be a release including this update?

**Comment by KazuCocoa** [comment]
Just published the latest master as 0.37.
Please check it.

**Comment by nunessf** [comment]
I think it's missing an update on version.py file, because this exception is being thrown:

> IOError: [Errno 2] No such file or directory: 'appium\\version.py'

**Comment by KazuCocoa** [comment]
0.37 package had below python file.mm let me tweak related code.

image

**Comment by KazuCocoa** [comment]
I hope this works on your environment...

Below was my env downloaded the module from https://pypi.org/project/Appium-Python-Client/0.38/#files

```
>>> import appium.common.helper as h
>>> h.library_version()
'0.38'
``

**Comment by nunessf** [comment]
Alright, it's working now, I'm able to use set_location. Thank you!

**Pull request merged**
