### PR TITLE
Avoid setting coordinates to null for touch actions

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Addresses https://github.com/appium/python-client/issues/213

### CODE REVIEW

**Comment by mylesbarros** [comment]
Is there an estimate when this will appear in a release?

**Comment by gwsu2008** [comment]
Please make a release with this fix. This bug is blocking the Appium 1.8.1 upgrade.

**Comment by romansvesh** [comment]
What do you waiting for? This bug blocks our upgrade too.

**Comment by gwsu2008** [comment]
Due to this bug on Appium Python Client 0.26 we can't use Appium 1.8.1.

**Comment by jlipps** [comment]
ping @imurchie

**Comment by romansvesh** [comment]
ping @mykola-mokhnach

**Comment by KazuCocoa** [comment]
This change fix below case. Your case looks different. @romansvesh 
```
{"action":"moveTo","options":{"y":null,"x":null,"element":"xxxx"}},{"action":"release","options":{}}]}
```

**Pull request merged**
