### PR TITLE
Update python-client README to account for XCUITest-related changes

### PR DESCRIPTION
**Pull request by emil-petersen**

### CODE REVIEW

**Comment by imurchie** [comment]
Awesome! Thanks!

Can you sign the CLA so we can get this in?

**Comment by emil-petersen** [comment]
@imurchie Just getting confirmation from my corporate IP guy, but it shouldn't be a problem. Sorry for the hold-up.

**Comment by imurchie** [comment]
No problem whatsoever!

**Comment by emil-petersen** [comment]
@imurchie All taken care of.

**Comment by imurchie** [comment]
Awesome! Thank you very much for this!

**Pull request merged**
