### PR TITLE
Add back `set_value` and remove deprecated mark

### PR DESCRIPTION
**Pull request by easyteacher**
Otherwise there is no way to change a slider's value in Appium tests.

This partially reverts https://github.com/appium/python-client/pull/909

Ref: https://invent.kde.org/sdk/selenium-webdriver-at-spi/-/blob/f17f6fbbe7175e96ceb89ea3426901875d20228a/selenium-webdriver-at-spi.py#L735

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Have you tried `element.send_keys`? The endpoint to UIA2 server is https://github.com/appium/appium-uiautomator2-driver/blob/b3dd0a2738543a0ce3ceeb6d3dfe8aa2918977d4/lib/commands/element.js#L68-L74 that is the same as https://github.com/appium/appium/blob/master/packages/base-driver/lib/protocol/routes.js#L234-L248 (element.send_keys)

**Comment by easyteacher** [comment]
Looks like the official webdriver does not really use set_value. But in  selenium-webdriver-at-spi send_keys and set_values map to "Send key input" and "atspi.valueElement.currentValue = value", so they are different.

**Comment by mykola-mokhnach** [comment]
The idea is to only have send_keys.

You can still have non-standard api if it is used with your particular driver by adding an extension method to the driver. Check https://github.com/appium/python-client/blob/fa7ba6ee5ee91c914f69e34547993af62995462f/test/unit/webdriver/webdriver_test.py#L210 as an example

**Comment by easyteacher** [comment]
Nice, didn't know that. Thanks for pointing out.

**Pull request closed without merging**
