### PR TITLE
Implemented set_location() - gps spoofing

### PR DESCRIPTION
**Pull request by jwallis**
iOS: Sometimes the call hangs if you are using an app that is requesting/using location (a UIAutomaion issue)
Android: I could not test because I cannot get the emulator working on my machine, but it should work

### CODE REVIEW

**Comment by jwallis** [comment]
Let me know if I should have done this PR differently

**Comment by jlipps** [comment]
@jwallis isn't `location` already a part of the webdriver client?

**Comment by imurchie** [comment]
The situation is a bit odd. The WebDriver client implements the [command end point](https://code.google.com/p/selenium/source/browse/py/selenium/webdriver/remote/command.py#122) and the [link to the correct point in the JSON Wire Protocol](https://code.google.com/p/selenium/source/browse/py/selenium/webdriver/remote/remote_connection.py#290). But it doesn't actually implement any method that allows one to call it. 

So part of this PR is needed. Not sure if we want to keep it all in the Appium client for now, so it is not confusing.

**Comment by jlipps** [comment]
we should contribute it to the selenium project too

**Comment by jlipps** [comment]
(cc @lukeis do you know why this situation exists?)

**Comment by jwallis** [comment]
I've been generally unclear as to what selenium functionality should be wrapped and what should not.  As @imurchie said, you can use it... if you can discover that it exists.

**Comment by jwallis** [comment]
Ok I think I get it now. Since selenium defines SET_LOCATION and its routing, the method should probably just be moved there.

**Comment by lukeis** [comment]
This doesn't match the current Java bindings:

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/html5/RemoteLocationContext.java#L48

Which from how I read it (sorry, didn't test it) would send the data payload as:
    { "location": {"latitude": latitude_value, "longitude": longitude_value, "altitude": altitude_value} }

And yes, this should probably get into the main selenium project, but seems like appium might not have implemented this the same as the existing api?

**Comment by lukeis** [comment]
as far as the why, this is an endpoint thrown together by the googlers and wasn't well defined and since no one was requesting it in python, only the commands were listed.  Allowing one if they were so inclined to do this directly:

    driver.execute(Command.SET_LOCATION, {....})

**Comment by jlipps** [comment]
> but seems like appium might not have implemented this the same as the existing api?

I think we did, we use the built-in location commands in the other selenium clients that have them.

> as far as the why, this is an endpoint thrown together by the googlers and wasn't well defined and since no one was requesting it in python, only the commands were listed. Allowing one if they were so inclined to do this directly

makes sense, we should contribute this to the selenium python client then

**Comment by imurchie** [comment]
I think @lukeis is correct about this PR having the wrong payload. Here we'll get

```json
{
    "latitude": "latitude_value", 
    "longitude": "longitude_value"
}
```

rather than as the [spec](https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/location) says

```json
{ 
    "location": {
        "latitude": latitude_value, 
        "longitude": longitude_value, 
        "altitude": altitude_value
    }
 }
```

The first ought to produce a deprecation warning in Appium (see [here](https://github.com/appium/appium/blob/master/lib/server/controller.js#L834))

**Comment by jwallis** [comment]
Ugh, you're right.  I did not notice the warning before but see it now, sorry.

**Comment by saltpy** [comment]
I think I have submitted that with the altitude fix in there - I'm hoping this can get fixed and out as I am depending on the functionality.

**Comment by imurchie** [comment]
Closed with #82.

**Pull request closed without merging**
