### PR TITLE
Add an endpoint for pressing buttons

### PR DESCRIPTION
**Pull request by dcnt**
Method for _mobile: pressButton_ has been added.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Thanks. Can you sign the CLA? @dcnt

**Comment by dcnt** [comment]
@KazuCocoa 
Hm, 
I signed it, but it's still in "pending" state, I guess, due to a mess with my email addresses.

**Comment by avk-ua** [comment]
@KazuCocoa 
Done.
Thanks.

**Comment by KazuCocoa** [comment]
thanks!

**Pull request merged**
