### PR TITLE
Support send sms

### PR DESCRIPTION
**Pull request by ki4070ma**
For https://github.com/appium/python-client/issues/350

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@KazuCocoa @imurchie @jlipps What do you think about adding @ki4070ma to the official list of Python client maintainers?

**Comment by KazuCocoa** [comment]
Sounds good to me

**Comment by nithinmohan114** [comment]
Will these changes available on the latest update?

**Comment by KazuCocoa** [comment]
Just released.
https://github.com/appium/python-client/blob/master/CHANGELOG.rst

**Pull request merged**
