### PR TITLE
add toggle wifi command

### PR DESCRIPTION
**Pull request by joshuazhusince1986**
the toggle wifi command is added according to https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L489.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
@joshuazhusince1986 
Could you sign the cla?

**Comment by joshuazhusince1986** [comment]
@KazuCocoa , thanks for review and approval !

**Comment by KazuCocoa** [comment]
@joshuazhusince1986 
Is your signed email different from your commit's one?
(Since the CIA is pending.)

**Comment by joshuazhusince1986** [comment]
@KazuCocoa , Double checked, cla should be signed correctly, no pending checks now !

**Comment by KazuCocoa** [comment]
🆒 
thanks!

**Pull request merged**
